### ISSUE TITLE
Re-open - Out of Balance Distribution #69 -  Distributions are still out of balance on Payment inserts with AMT included. 

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#130]
This is still not working.  I can forward my sample text but it exactly matches the sample using a cash type paycode. 

Many thanks, 

Bill

**Comment by Bflatt** [comment]
Mike,   I also checked the old bug #43 with new api and it is also still not working.   Perhaps I have not gotten the correct code.  My version is now 2.1.243.1

**Comment by Bflatt** [comment]
if this is corrected in the NEW 2.1.243 api could you please provide a correctly formatted json script?  The sample json in documentation results in an out of balance distribution when posting any transaction which includes an amount.  "AMT":"5.00"

**Comment by blueoceanyyc** [comment]
Is there any update on this? We are using the latest version of the API and experience similar issues with out of balance payments in the drawer. Please advise or assist in us resolving this issue.

**Comment by Bflatt** [comment]
This has never been resolved.


Regards,

Bill

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x109 | Local: 918.317.0707 | Fax: 918-900-2231
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net/> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by langillerr** [comment]
We are still experiencing this as well.

**Comment by OzzDizz** [comment]
Still experiencing this problem as well. In the other 'closed' issue Mike said it would come on a future release, we're on a new release and it does not seem to be possible to send any payment info at all.

The payments show up on the order/ticket, but the amount due is still there and everything is out of balance.

**Comment by OzzDizz** [comment]
In reviewing the distributions report we found the following.
Adding a payment to an order via the CounterPoint GUI, and posting the drawer, creates the following distributions:
DEBIT (Bank) Payment received
CREDIT (Liability) Deposits received

Adding a payment to an order via the CounterPoint API, and posting the drawer, creates the following distributions:
DEBIT (Bank) Payment received
CREDIT: Nothing. There is no corresponding credit.

This is why the distributions are out of balance.

We have tried playing with all the payment fields -        
       "FINAL_PMT"
       "DEP_LIN_COPIED_TO_REL_DOC" 
       "CARD_IS_NEW"
       "EXCH_LOSS"
       "SECURE_ECOMM_TRX"

Trying all the possible values and combinations or omitting them entirely.

The out of balance distributions remain.

I believe in large part the API is intended to allow creating orders and receiving online payments. This is critical functionality that appears to be broken, rendering the API likely unusable for most ecommerce applications.

**Comment by mm185253** [comment]
This issue is resolved in the CPAPI v2.3 release.
